# Generated by Django 4.1.3 on 2022-12-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('game', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
        ),
    ]
