# Generated by Django 4.1.3 on 2023-02-19 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumps',
            name='expiry',
            field=models.DateField(default=datetime.date(2023, 2, 20)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username already taken. (Panda)'}, max_length=20, unique=True),
        ),
    ]
