# Generated by Django 4.1.3 on 2023-01-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bumps',
            old_name='listing',
            new_name='listing1',
        ),
        migrations.RenameField(
            model_name='bumps',
            old_name='user',
            new_name='user1',
        ),
    ]
