# Generated by Django 4.1.3 on 2022-12-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='game',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='server_likes', to='website.tag')),
            ],
        ),
    ]
