# Generated by Django 4.1.3 on 2023-01-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_listing_bumps_listing1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bumps',
            old_name='listing1',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='bumps',
            old_name='user1',
            new_name='user',
        ),
    ]
