# Generated by Django 4.1.3 on 2023-02-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_bumps_expiry_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email already taken. (Cobra)'}, max_length=254, unique=True),
        ),
    ]
