# Generated by Django 4.1.3 on 2023-01-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_listing1_bumps_listing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bumps',
        ),
    ]
