# Generated by Django 4.1.3 on 2022-12-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_game_tags_serverlisting_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlisting',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='server_tags', to='website.tag'),
        ),
    ]
