# Generated by Django 4.1.3 on 2023-02-27 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_bumps_expiry_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='bumps',
            name='expiry',
            field=models.DateField(default=datetime.date(2023, 2, 28)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(error_messages={'required': 'Tag name is required. (Parrot)', 'unique': 'Tag already taken. (Parrot)'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(error_messages={'required': 'Tag slug is required. (Parrot)', 'unique': 'Tag slug already taken. (Parrot)'}, max_length=20, unique=True),
        ),
    ]
