# Generated by Django 4.1.3 on 2022-12-16 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_alter_serverlisting_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlisting',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_listings', to='website.game'),
        ),
        migrations.AlterField(
            model_name='serverlisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
