# Generated by Django 4.1.3 on 2023-02-01 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_bumps'),
    ]

    operations = [
        migrations.AddField(
            model_name='bumps',
            name='expiry',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
