# Generated by Django 4.1.3 on 2022-12-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_serverlisting_game_alter_serverlisting_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlisting',
            name='tags',
            field=models.ManyToManyField(blank=True, to='website.tag'),
        ),
    ]
