# Generated by Django 4.1.3 on 2022-12-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_serverlisting_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(to='website.tag'),
        ),
        migrations.AddField(
            model_name='serverlisting',
            name='discord',
            field=models.CharField(default='wwww.discord.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serverlisting',
            name='long_description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='serverlisting',
            name='short_description',
            field=models.TextField(max_length=200),
        ),
    ]
