# Generated by Django 4.1.3 on 2023-02-01 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_bumps_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumps',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bumps',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 18, 41, 30, 805845)),
        ),
    ]
