# Generated by Django 4.1.3 on 2023-02-01 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_bumps_date_added_alter_bumps_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumps',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 18, 48, 19, 389338)),
        ),
    ]
