# Generated by Django 4.1.3 on 2023-01-11 17:45

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0011_remove_game_title_game_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverlisting',
            name='likes',
        ),
        migrations.AddField(
            model_name='serverlisting',
            name='bumps',
            field=models.ManyToManyField(blank=True, related_name='server_bumps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serverlisting',
            name='last_bump',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
