# Generated by Django 4.1.3 on 2023-02-01 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_bumps_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumps',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 19, 7, 32, 16540)),
        ),
    ]
