# Generated by Django 4.1.3 on 2023-02-02 12:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_images_approved_by_alter_images_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumps',
            name='expiry',
            field=models.DateField(default=datetime.date(2023, 2, 3)),
        ),
        migrations.AlterField(
            model_name='images',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
