# Generated by Django 4.1.3 on 2023-02-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_customuser_is_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unapproved'), (1, 'Approved'), (2, 'Rejected'), (3, 'Rejected and User banned')], default=0),
        ),
    ]
