# Generated by Django 4.1.3 on 2023-02-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_images_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
