# Generated by Django 4.1.3 on 2023-02-04 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_rename_approved_by_images_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='public_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bumps',
            name='expiry',
            field=models.DateField(default=datetime.date(2023, 2, 5)),
        ),
    ]
