# Generated by Django 4.1.3 on 2023-02-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_bumps_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
