# Generated by Django 4.1.3 on 2023-02-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_game_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image_public_id',
        ),
    ]
