# Generated by Django 4.1.3 on 2023-02-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
