# Generated by Django 4.1.3 on 2023-02-07 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumps',
            name='expiry',
            field=models.DateField(default=datetime.date(2023, 2, 8)),
        ),
    ]
