# Generated by Django 4.1.3 on 2023-02-07 14:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_alter_bumps_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlisting',
            name='long_description',
            field=tinymce.models.HTMLField(max_length=2000),
        ),
    ]
