# Generated by Django 4.1.3 on 2023-02-10 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_alter_bumps_expiry_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlisting',
            name='bump_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bumps',
            name='expiry',
            field=models.DateField(default=datetime.date(2023, 2, 11)),
        ),
    ]
