# Generated by Django 4.1.3 on 2023-02-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_serverlisting_bump_count_alter_bumps_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlisting',
            name='tiktok',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
