# Generated by Django 4.1.3 on 2023-02-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_serverlisting_tiktok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlisting',
            name='tiktok',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
