# Generated by Django 4.1.3 on 2023-02-18 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_alter_bumps_expiry_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumps',
            name='expiry',
            field=models.DateField(default=datetime.date(2023, 2, 19)),
        ),
    ]
